<a href="https://colab.research.google.com/github/jomariy241/daily-task/blob/main/pandas7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df =pd.read_csv('/content/Death_rates_for_suicide__by_sex__race__Hispanic_origin__and_age__United_States.csv')
df

,INDICATOR,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,FLAG
0,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.000,1950,1,All ages,0.0,13.2,NaN
1,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.000,1960,2,All ages,0.0,12.5,NaN
2,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.000,1970,3,All ages,0.0,13.1,NaN
3,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.000,1980,4,All ages,0.0,12.2,NaN
4,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.000,1981,5,All ages,0.0,12.3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6385,Death rates for suicide,"Deaths per 100,000 resident population, crude",2,"Sex, age and race and Hispanic origin (Single ...",11,Female: Not Hispanic or Latino: Black or Afric...,7.225,2018,42,65 years and over,5.0,1.3,NaN
6386,Death rates for suicide,"Deaths per 100,000 resident population, crude",2,"Sex, age and race and Hispanic origin (Single ...",11,Female: Hispanic or Latino: All races: 15-24 y...,7.232,2018,42,15-24 years,2.0,4.1,NaN
6387,Death rates for suicide,"Deaths per 100,000 resident population, crude",2,"Sex, age and race and Hispanic origin (Single ...",11,Female: Hispanic or Latino: All races: 25-44 y...,7.233,2018,42,25-44 years,3.0,4.4,NaN
6388,Death rates for suicide,"Deaths per 100,000 resident population, crude",2,"Sex, age and race and Hispanic origin (Single ...",11,Female: Hispanic or Latino: All races: 45-64 y...,7.234,2018,42,45-64 years,4.0,3.2,NaN
6389,Death rates for suicide,"Deaths per 100,000 resident population, crude",2,"Sex, age and race and Hispanic origin (Single ...",11,Female: Hispanic or Latino: All races: 65 year...,7.235,2018,42,65 years and over,5.0,1.6,NaN

In [ ]:
print(df.head())

                 INDICATOR                                               UNIT  \
0  Death rates for suicide  Deaths per 100,000 resident population, age-ad...
1  Death rates for suicide  Deaths per 100,000 resident population, age-ad...
2  Death rates for suicide  Deaths per 100,000 resident population, age-ad...
3  Death rates for suicide  Deaths per 100,000 resident population, age-ad...
4  Death rates for suicide  Deaths per 100,000 resident population, age-ad...

   UNIT_NUM STUB_NAME  STUB_NAME_NUM   STUB_LABEL  STUB_LABEL_NUM  YEAR  \
0         1     Total              0  All persons             0.0  1950
1         1     Total              0  All persons             0.0  1960
2         1     Total              0  All persons             0.0  1970
3         1     Total              0  All persons             0.0  1980
4         1     Total              0  All persons             0.0  1981

   YEAR_NUM       AGE  AGE_NUM  ESTIMATE FLAG
0         1  All ages      0.0      13.2  NaN
1         2  All ages      0.0      12.5  NaN
2         3  All ages      0.0      13.1  NaN
3         4  All ages      0.0      12.2  NaN
4         5  All ages      0.0      12.3  NaN

In [ ]:
print(df.describe())

          UNIT_NUM  STUB_NAME_NUM  STUB_LABEL_NUM         YEAR     YEAR_NUM  \
count  6390.000000    6390.000000     6390.000000  6390.000000  6390.000000
mean      1.872926       4.621909        4.686775  1997.525822    22.692019
std       0.333081       2.031777        1.829624    14.937451    12.286033
min       1.000000       0.000000        0.000000  1950.000000     1.000000
25%       2.000000       3.000000        3.230000  1988.000000    12.000000
50%       2.000000       5.000000        5.125100  1999.000000    23.000000
75%       2.000000       6.000000        6.153000  2009.000000    33.000000
max       2.000000      11.000000        7.235000  2018.000000    42.000000

           AGE_NUM     ESTIMATE
count  6390.000000  5484.000000
mean      2.712207    13.709810
std       1.932280    11.531805
min       0.000000     0.300000
25%       0.000000     5.000000
50%       3.000000    10.500000
75%       4.100000    19.500000
max       6.000000    74.800000

In [ ]:
df.shape

(6390, 13)

In [ ]:
df.dtypes

INDICATOR          object
UNIT               object
UNIT_NUM            int64
STUB_NAME          object
STUB_NAME_NUM       int64
STUB_LABEL         object
STUB_LABEL_NUM    float64
YEAR                int64
YEAR_NUM            int64
AGE                object
AGE_NUM           float64
ESTIMATE          float64
FLAG               object
dtype: object

In [ ]:
mv=df.isnull().sum()
mv[mv>0]

ESTIMATE     906
FLAG        5484
dtype: int64

In [ ]:
df.nunique()

INDICATOR           1
UNIT                2
UNIT_NUM            2
STUB_NAME          12
STUB_NAME_NUM      12
STUB_LABEL        161
STUB_LABEL_NUM    161
YEAR               42
YEAR_NUM           42
AGE                15
AGE_NUM            15
ESTIMATE          529
FLAG                2
dtype: int64

In [ ]:
df.columns

Index(['INDICATOR', 'UNIT', 'UNIT_NUM', 'STUB_NAME', 'STUB_NAME_NUM',
       'STUB_LABEL', 'STUB_LABEL_NUM', 'YEAR', 'YEAR_NUM', 'AGE', 'AGE_NUM',
       'ESTIMATE', 'FLAG'],
      dtype='object')

In [ ]:

df['UNIT'].unique()

array(['Deaths per 100,000 resident population, age-adjusted',
       'Deaths per 100,000 resident population, crude'], dtype=object)

In [ ]:
column='ESTIMATE'
df[column].mean()

13.709810357403356

In [ ]:
df[column].median()

10.5

In [ ]:
df[column].std()

11.531805309076454

In [ ]:
column='ESTIMATE'
q1=df[column].quantile(0.25)
q3=df[column].quantile(0.75)
iqr=q3-q1
outliers=df[(df['ESTIMATE'] <q1) | (df['ESTIMATE'] >q3)]['ESTIMATE']
outliers

42      21.2
43      20.0
44      19.8
45      19.9
46      19.8
        ...
6385     1.3
6386     4.1
6387     4.4
6388     3.2
6389     1.6
Name: ESTIMATE, Length: 2731, dtype: float64

In [ ]:
columns=['ESTIMATE','STUB_NAME_NUM','AGE_NUM','STUB_NAME_NUM']
df[columns].corr()

               ESTIMATE  STUB_NAME_NUM   AGE_NUM  STUB_NAME_NUM
ESTIMATE       1.000000      -0.041625  0.325693      -0.041625
STUB_NAME_NUM -0.041625       1.000000  0.018175       1.000000
AGE_NUM        0.325693       0.018175  1.000000       0.018175
STUB_NAME_NUM -0.041625       1.000000  0.018175       1.000000

In [ ]:
category=df.groupby('UNIT_NUM')

In [ ]:
category.agg({'ESTIMATE':['mean','sum'],'STUB_NAME_NUM':['mean','sum'],'AGE_NUM':['mean','sum'],'STUB_NAME_NUM':['mean','sum']})

           ESTIMATE          STUB_NAME_NUM          AGE_NUM
               mean      sum          mean    sum      mean      sum
UNIT_NUM
1         10.270816   7425.8      4.522167   3672  0.000000      0.0
2         14.232052  67758.8      4.636429  25862  3.107028  17331.0

In [ ]:
analyzing a dataset related to death rates for suicide by sex, race, Hispanic origin, and age in the United States.
.The dataset provides various statistical measures such as mean, median, and standard deviation for the 'ESTIMATE' column, which likely represents death rates for suicide.
.Outliers in the 'ESTIMATE' column were identified using the interquartile range (IQR) method, suggesting the presence of data points that deviate significantly from the majority of the data.
.The correlation matrix indicates how different columns such as 'ESTIMATE', 'STUB_NAME_NUM', and 'AGE_NUM' are related to each other. This could provide insights into potential relationships between age, demographic factors, and suicide rates.
.By grouping the data by 'UNIT_NUM' and aggregating statistics for 'ESTIMATE', 'STUB_NAME_NUM', and 'AGE_NUM', the analysis offers a summarized view of the data segmented by different units, which could represent demographic or geographic segments.